window.lessonScenes = [

{
    type: "Summary",
        intro: `
        `
},



<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_01.webm"  type="video/webm">    </video>     <figcaption>      	<p lang="ja" class="Japanese">あ</p>      	<p lang="en" class="English">Huh?</p>    	</figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_02.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">はい？</p>      <p lang="en" class="English">Huh?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_03.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ママ、どっち？</p>      <p lang="en" class="English">Which way is Mama?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_04.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">どっち、どっち？</p>      <p lang="en" class="English">Which way is home?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_05.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ママ、ママー</p>      <p lang="en" class="English">Mama! Mama!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_06.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ママ　どこか、知ってる？</p>      <p lang="en" class="English">Do you know where Mama is?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_07.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あ、あ、 はあー、びっくりしたあー</p>      <p lang="en" class="English">Ah, that startled me.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_08.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">こっ　こわあー！</p>      <p lang="en" class="English">S-Scary!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_09.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うち　帰る～</p>      <p lang="en" class="English">I'm going home.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_10.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うち、どこー</p>      <p lang="en" class="English">I wonder where home is...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_11.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うち、知ってる？</p>      <p lang="en" class="English">Do you know where home is?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_12.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">おなか　すいたー</p>      <p lang="en" class="English">I'm hungry...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_13.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うち、わかんない</p>      <p lang="en" class="English">I dunno... where home is.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_14.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">きみも　うち、わかんないんだね～</p>      <p lang="en" class="English">You don't know where home is either, do you?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_15.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">洋平！</p>      <p lang="en" class="English">Youhei!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_16.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">転んでも、自分で　起きるんだよ～</p>      <p lang="en" class="English">If you fall over, you get up by yourself!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_17.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">お母さん～</p>      <p lang="en" class="English">Mommy.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_18.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">猫、転んでいる</p>      <p lang="en" class="English">The kitty fell over.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E1_19.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">大変、どうしたの　かしら～</p>      <p lang="en" class="English">Oh no! I wonder what happened?</p>    </figcaption>  </figure>  <hr>

  <h2>Chi's Sweet Home — Episode 02</h2>

<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_20.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うち、帰る。ママ～</p>      <p lang="en" class="English">I'm going home, Mama.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_21.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">はい？</p>      <p lang="en" class="English">Huh?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_22.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ここ　どこ？</p>      <p lang="en" class="English">Where is this?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_23.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">猫だん 動いている</p>      <p lang="en" class="English">Kitty is moving!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_24.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">くさのとこ、落ちてたのだ～</p>      <p lang="en" class="English">You're the one that fell at the grassy place!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_25.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">なんで　君も　ここに　いるの？</p>      <p lang="en" class="English">Why are you here too?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_26.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">お～気が付いたか</p>      <p lang="en" class="English">Oh, you've woken up?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_27.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">元気出たのかな？</p>      <p lang="en" class="English">Are you feeling better?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_28.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">行き止まりだ～</p>      <p lang="en" class="English">It's a dead end!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_29.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">おちゃ～　驚かせちゃったな～</p>      <p lang="en" class="English">Oh dear. I wonder if we scared it?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_30.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あはは、なに　それ？</p>      <p lang="en" class="English">What's that?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_31.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うん、おなか、すいてるんじゃないかと　思って</p>      <p lang="en" class="English">I thought it might be hungry.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_32.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">飲んでくれる　かな～</p>      <p lang="en" class="English">I wonder if it will drink.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_33.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">なんか、おいしそうな匂いや</p>      <p lang="en" class="English">I smell something yummy!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_34.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">はあ、ミルクだ！</p>      <p lang="en" class="English">Oh! Milk!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_35.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">は～ 猫だん　飼うの？</p>      <p lang="en" class="English">Are we keeping kitty?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_36.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うん～　うちのマンション、犬や猫が　禁止だ　からなあ～</p>      <p lang="en" class="English">Well you see, dogs and cats aren't allowed in our apartment.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_37.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うちでは　無理だから、だれか貰い手を探さなくちゃね</p>      <p lang="en" class="English">It won't work here, so we'll have to find someone to take it.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_38.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ぽんぽんだ～</p>      <p lang="en" class="English">I'm full!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_39.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うち　帰る！</p>      <p lang="en" class="English">I'm going home!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_40.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">猫だん、お外に　出たいの？</p>      <p lang="en" class="English">Kitty, do you want to go outside?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_41.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あ、うち、あ、うち、あ、うち～</p>      <p lang="en" class="English">Home! Home! Home!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_42.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あ、うち、あ、うち、あ？</p>      <p lang="en" class="English">Home! Home! A-Ah...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_43.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">洋平、管理人さんに　見つかっちゃう　でしょう～</p>      <p lang="en" class="English">Youhei! It will be caught by the landlord, right?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_44.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">どうした？</p>      <p lang="en" class="English">What's wrong?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Chi's Sweet Home/AV_Chi's_Sweet_Home_S01_E2_45.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">もうちょっと　だけ　ここに　隠れていようと</p>      <p lang="en" class="English">I'll hide here just a little bit longer.</p>    </figcaption>  </figure>  <hr>


  
</body>
];


 
];