window.lessonScenes = [

{
    type: "Summary",
        intro: `
        `
},



<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_001.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">どこか　遠い　知らない場所で　僕は　彼女を　捜していた</p>      <p lang="en" class="English">Somewhere far away and unknown, I was searching for her.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_002.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">僕が　彼女を　捜しているのは　彼女が　僕を　捜しているから　だ</p>      <p lang="en" class="English">I was searching for her because she was searching for me.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_003.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">彼女の匂い</p>      <p lang="en" class="English">It's her scent.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_004.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">重い　鉄の扉　その　向こうに…</p>      <p lang="en" class="English">On the other side of that heavy iron door lies...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_005.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">長い　間　ありがとう　ね</p>      <p lang="en" class="English">Thanks for staying with me for so long.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_006.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">そんな…　こっちこそ　ごめんね　先に　出ていくなんて</p>      <p lang="en" class="English">No, no! I should apologize for moving out first.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_007.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あたしから　ルームシェアを　誘ったのに…</p>      <p lang="en" class="English">I was the one who invited you to live with me.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_008.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いい　ってば　私も　それで　助かったんだし</p>      <p lang="en" class="English">It's okay. Sharing this place helped me out a lot.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_009.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">１年半かぁ</p>      <p lang="en" class="English">A year and a half, huh?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_010.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">フフフ…　何か　あっ　と　言う間だったね</p>      <p lang="en" class="English">It flew by so fast.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_011.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ニャ～ おっ　ダル～</p>      <p lang="en" class="English">Hey, Daru!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_012.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">起きたの？</p>      <p lang="en" class="English">You're awake?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_013.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">なになに？　サヨナラ　してくれるの～？</p>      <p lang="en" class="English">What's this? Did you come to say goodbye to me?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_014.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ダル～</p>      <p lang="en" class="English">Daru...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_015.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ありゃ</p>      <p lang="en" class="English">Aww...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_016.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">アハハハ　結局あたしに　は　懐かなかったなぁ</p>      <p lang="en" class="English">He never really came to like me.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_017.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あ　もう　行かなきゃ</p>      <p lang="en" class="English">Oh, I have to go.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_018.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">彼氏さんに　よろしく　ね</p>      <p lang="en" class="English">Tell your boyfriend I said hi.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_019.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うん</p>      <p lang="en" class="English">Sure.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_020.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">頑張ってね</p>      <p lang="en" class="English">Good luck with everything.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_021.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うん…　知歌も</p>      <p lang="en" class="English">You too, Tomoka.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_022.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あんたも　長生きしてよ　もう　おじいちゃんなんだから</p>      <p lang="en" class="English">And you'd better live a long life! You're an old man already.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_023.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">じゃあ　ね</p>      <p lang="en" class="English">Bye.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_024.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">大好きな彼女</p>      <p lang="en" class="English">I love her.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_025.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">僕は　彼女の猫だ</p>      <p lang="en" class="English">I'm her cat.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_026.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">夏の　一番　暑い　日</p>      <p lang="en" class="English">It was the hottest day of summer.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_027.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">行っちゃったね</p>      <p lang="en" class="English">She's gone...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_028.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">新しい　部屋も　探さなきゃね</p>      <p lang="en" class="English">We'll have to look for a new place.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_029.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">一緒に　暮らしていた　彼女の友達が　出ていった 僕と　彼女の　暮らしが　始まる</p>      <p lang="en" class="English">The friend she was living with moved out, and life with just the two of us began.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_030.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">彼女は　毎朝いつも　きちんと　決まった時間に　起きて ゴハンを　用意してくれる</p>      <p lang="en" class="English">Every morning, she wakes up at the  same time and prepares my breakfast.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_031.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いつも　のごちそう いつも　優しい　彼女</p>      <p lang="en" class="English">The meal is always the same, and she's always just as kind.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_032.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">毛並みを　きちんと　整えた彼女は　誰よりも　きれいで…</p>      <p lang="en" class="English">After putting her hair perfectly in place, no one is more beautiful than she.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_033.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">背筋を　伸ばし　彼女は　朝の光の中へ　と　歩き出す</p>      <p lang="en" class="English">She stands up straight and walks out into the bright morning light.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_034.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">行ってくるね</p>      <p lang="en" class="English">I'll be back soon.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_035.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">もしもし　お母さんだけど…</p>      <p lang="en" class="English">Hello? It's your mother.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_036.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">分かってるって</p>      <p lang="en" class="English">I know.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_037.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">だから…　しょうが　ない　でしょ　どこも　厳しい　んだし</p>      <p lang="en" class="English">What other choice do I have? Everywhere's expensive.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_038.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">帰らない</p>      <p lang="en" class="English">I won't come home.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_039.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ルームシェアだって言ってたのに　今さら　１人暮らしするなんて</p>      <p lang="en" class="English">You said you were going to get a roommate. Now you're just going to live alone?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_040.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">約束が　違うじゃ　ない　の</p>      <p lang="en" class="English">This wasn't the deal we agreed on.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_041.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">卒業まで　もう　すぐ　なんだし…</p>      <p lang="en" class="English">You'll be graduating soon, and...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_042.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ごめん　お風呂沸いたから はぁ…</p>      <p lang="en" class="English">Sorry. My bath's ready.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_043.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">御社を　志望した理由と　しましては…</p>      <p lang="en" class="English">The reason I applied to this company is because...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_044.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">小さい　頃から　本が　好きで　特に　絵本の仕事に　憧れており…</p>      <p lang="en" class="English">I've loved books since I was little,  and I'm especially interested in making picture books.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_045.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">私は　小さい　頃から　動物が　好きで…</p>      <p lang="en" class="English">I've loved animals since I was little...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_046.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">小さい　頃から　家が　好きで　不動産の仕事に　憧れて…</p>      <p lang="en" class="English">I've loved homes since I was little,  and I always wanted to work in real estate...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_047.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ない　よねぇ</p>      <p lang="en" class="English">Yeah, that won't work.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_048.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">頑張ってるんだよ　私…</p>      <p lang="en" class="English">I am doing my best.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_049.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">何だか　いろいろ　分からなくなっちゃった</p>      <p lang="en" class="English">I don't understand anything anymore.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_050.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">彼女の抱えた痛みが　僕の体に　伝わる</p>      <p lang="en" class="English">The pain she feels transfers over to me.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_051.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">彼女の痛みを　僕は　どう　することも　できない</p>      <p lang="en" class="English">But I can't do anything to ease her pain.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_052.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">次の日　彼女は　いつも　と　同じ　ように… ニャ～ きれいで　優しく…</p>      <p lang="en" class="English">The next day, just like every other, she's beautiful and kind...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_053.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">おはよう　ダル</p>      <p lang="en" class="English">Morning, Daru.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_054.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">僕の大好きな　ほほえみを　浮かべていた</p>      <p lang="en" class="English">...as she shows me that lovely smile.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_055.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">彼女は　今日も　背筋を　ぴん　と　伸ばし　重い　扉を　開ける</p>      <p lang="en" class="English">Yet again, she stands up straight and opens that heavy door.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_056.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">扉の向こうの　不完全で　少し　残酷な世界</p>      <p lang="en" class="English">On the other side of the door is an  imperfect and somewhat cruel world.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_057.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">そんな　世界を　精いっぱい　好きになろう　としている彼女</p>      <p lang="en" class="English">She's doing her best to learn to love that world.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/She_and_Her_Cat_Everything_Flows_E1/AV_She_and_Her_Cat_S01_E1_058.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">僕は　そんな　彼女が　とても　好きだ</p>      <p lang="en" class="English">And for that, I love her very much.</p>    </figcaption>  </figure>  <hr>


  
</body>
];


 
];