window.lessonScenes = [

{
    type: "Summary",
        intro: `
        `
},


<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_01.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">はあ　はあ</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_02.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">……ここに、来るまでの間。</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_03.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ずっと願ってたよ。　どうか、ここにいるのが　君じゃないようにと…</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_04.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">そのダイヤを　どうするつもりだ！！</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_05.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">わかりきったこと　聞くんじゃねえ。</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_06.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">…敵と取引するつもりか！</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_07.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">中の「チップ」が敵の手に渡れば、どれだけの人が傷つくか…！</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_08.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">だから、なんだ？　他の奴らがどうなろうが知ったことか。</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_09.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">オレは壊す、奪う　侵す側の人間だ。</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_10.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">それなら…　どうして、あの時、僕を救った？</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_11.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ヒーローごっこはウンザリだ。　じゃあな。</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_12.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">止まれ！</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_13.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ハッ！</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_14.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">撃てや。できるもんならな。</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_15.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">トリガーを引く前に手首ごとぶった切ってやる！</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_16.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">同じだ。出会った時のやりとりと</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_17.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あれから、ずっと力を合わせて　ここまで来たのに！</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_18.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">餞別　に教えてやるよ。　ドギー。</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_19.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">敵の前で　そうやって隙を見せるのは</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_20.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">殺せっつってんのと　同じだ！！</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_21.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">やられる！</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_22.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">「チップ」は渡せない　あいつを行かせるわけには　いかない！</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_23.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">弾かれた！？</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_24.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">くっ</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_25.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">遅い！！</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_26.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">っ</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_27.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">待て　行かせ、ない</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_28.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ぐうっ</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_29.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">．．．う．．．</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_30.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">行、くな。　いっ　しょに</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_31.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">終わりだ。</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_32.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あばよ、「ヒーロー」。</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_33.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">待て……待って……くれ</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Bond Mission/G_Bond_Mission_E1_34.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">待ってくれ　アーロン</p>      <p lang="en" class="English"></p>    </figcaption>  </figure>  <hr>

  
</body>
];


 
];