window.lessonScenes = [

{
    type: "Summary",
        intro: `
        `
},



<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0001.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">暗い 暗い 暗い</p>      <p lang="en" class="English">It's dark, it's dark, it's dark!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0002.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">くーらーいー</p>      <p lang="en" class="English">It. Is. Dark.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0003.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うるせえ</p>      <p lang="en" class="English">Shut it.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0004.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ごめん</p>      <p lang="en" class="English">Sorry.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0005.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いいよ</p>      <p lang="en" class="English">It's okay.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0006.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">じゃあ　ランタン点けていいですか</p>      <p lang="en" class="English">Hey, can I turn on the lantern?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0007.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ダメ</p>      <p lang="en" class="English">No.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0008.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">そんな</p>      <p lang="en" class="English">Aw, man.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0009.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">節約しろ</p>      <p lang="en" class="English">Think about the oil.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0010.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">給油施設だって次どこにあるか分からないんだぞ</p>      <p lang="en" class="English">Who knows when we'll find the next refueling station?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0011.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">でもまあ　ずっと暗闇だから　目が慣れてきたかも</p>      <p lang="en" class="English">Well, I guess it's been dark long enough that my eyes have probably gotten used to it.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0012.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">もうずっと日の光を見てないからね</p>      <p lang="en" class="English">Yeah, we haven't seen daylight in ages.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0013.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">何日経ったかすら…</p>      <p lang="en" class="English">I wonder how many days it's been.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0014.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いやホント　どこにいるんだろうね　私たち</p>      <p lang="en" class="English">Man, where even are we right now?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0015.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">なんでこんな所にいるんだっけ</p>      <p lang="en" class="English">Why'd we come to a place like this, again?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0016.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ユー　お前な　あの穴に入ってみようとか言ってたのは誰ですか</p>      <p lang="en" class="English">Yuu, come on. Who was it that suggested going into that random tunnel?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0017.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ちーちゃんだっけ</p>      <p lang="en" class="English">It was you, right?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0018.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">お前だよ</p>      <p lang="en" class="English">It was you.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0019.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あれは　ほら　古い言葉にもあるじゃん</p>      <p lang="en" class="English">Well, isn't that, like, an old saying?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0020.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">確か「穴があったら入りたい」って</p>      <p lang="en" class="English">I wish I could crawl into a hole, or something?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0021.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">そういう意味の言葉だっけ　それ</p>      <p lang="en" class="English">Is that really what that means?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0022.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">とにかく出口を見つけないと</p>      <p lang="en" class="English">Anyway, we need to get out of here.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0023.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">食べ物もあんまりないしねー</p>      <p lang="en" class="English">We don't have much food left either, huh?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0024.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">まあ　出たとこで　食料が手に入るか分からないしね</p>      <p lang="en" class="English">Though it's not like we're sure to  find any even after getting out.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0025.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">どうなるんだろうね　私たち</p>      <p lang="en" class="English">Man, what's going to happen to us?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0026.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いつになったら一番上に</p>      <p lang="en" class="English">When are we going to finally get to the top?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0027.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ねえ 私も寝よう</p>      <p lang="en" class="English">Hey, Guess I'll sleep too.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0028.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ど…どうも</p>      <p lang="en" class="English">Really? For me?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0029.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">スープだって　どんな感じで？</p>      <p lang="en" class="English">Oh, is that so...?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0030.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ああ　それだったら</p>      <p lang="en" class="English">Well, if it's like that...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0031.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">暖かい</p>      <p lang="en" class="English">Ah, warmth.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0032.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">お腹すいた</p>      <p lang="en" class="English">I'm hungry.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0033.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">さむ</p>      <p lang="en" class="English">It's freezing.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0034.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">風が吹いてる</p>      <p lang="en" class="English">There's a draft!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0035.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ねえ　起きて おい　ユー</p>      <p lang="en" class="English">Hey, wake up! Hey, Yuu!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0036.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">そう　風が吹く方に進んでいけば…</p>      <p lang="en" class="English">So, if we go the way the wind's blowing...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0037.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">出口があるってこと？</p>      <p lang="en" class="English">We'll find an exit?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0038.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">そういうこと</p>      <p lang="en" class="English">That's how it works.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0039.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">どう</p>      <p lang="en" class="English">Well?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0040.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あっち</p>      <p lang="en" class="English">Thataway.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0041.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">よし</p>      <p lang="en" class="English">All right.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0042.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">次はあっち</p>      <p lang="en" class="English">That way next.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0043.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">分かった</p>      <p lang="en" class="English">Got it.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0044.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">光だ</p>      <p lang="en" class="English">Light!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0045.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">すごい</p>      <p lang="en" class="English">Wow!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0046.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">明るいよ　ちーちゃん</p>      <p lang="en" class="English">It's so bright, Chi-chan!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0047.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">夜だったんだ</p>      <p lang="en" class="English">So it was night.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0048.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ねえ　せっかく外に出たんだし　スープ飲もうよ　スープ</p>      <p lang="en" class="English">Hey, since we've finally made it out, let's have ourselves some soup!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0049.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">じゃあ　出られた記念ということで</p>      <p lang="en" class="English">Fine, I guess it is something to celebrate.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0050.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">やったー　ご飯</p>      <p lang="en" class="English">Hooray, food!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0051.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">もういいんじゃない</p>      <p lang="en" class="English">Has to be done by now, right?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0052.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">そうだな</p>      <p lang="en" class="English">Yeah, I think so.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0053.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">はい　最後の１缶だからな</p>      <p lang="en" class="English">Here. It's the last can, okay?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0054.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うん</p>      <p lang="en" class="English">Yep!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0055.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あちっ</p>      <p lang="en" class="English">Ow!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0056.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">おいしいー</p>      <p lang="en" class="English">Yummy!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0057.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">知らなかったね　夜がこんなに明るいなんて</p>      <p lang="en" class="English">I never knew it could be this bright at night.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0058.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ずっと暗い穴の中にいたからね</p>      <p lang="en" class="English">It's because we were in the dark for so long.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0059.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">光に敏感になってるんだよ</p>      <p lang="en" class="English">We've become sensitive to light.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0060.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">じゃあ　これで日が昇ってきたらどうなっちゃうの</p>      <p lang="en" class="English">Then what's going to happen to us when the sun rises?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0061.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">焼け死ぬ</p>      <p lang="en" class="English">We'll burn to death.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0062.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うるさい</p>      <p lang="en" class="English">Shut up!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0063.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ヒット</p>      <p lang="en" class="English">Hit.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0064.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ヒット</p>      <p lang="en" class="English">Hit.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0065.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">外れ</p>      <p lang="en" class="English">Miss.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0066.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ありゃ</p>      <p lang="en" class="English">Oh?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0067.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">じゃあ　ラスト</p>      <p lang="en" class="English">All right, last one.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0068.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">もっと撃ってもいいよ</p>      <p lang="en" class="English">You can keep going if you want.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0069.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ヒット</p>      <p lang="en" class="English">Hit.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0070.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ヒット</p>      <p lang="en" class="English">Hit.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0071.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ヒット</p>      <p lang="en" class="English">Hit.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0072.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ちーちゃんも撃つかい</p>      <p lang="en" class="English">You want a go?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0073.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いや　私はいい</p>      <p lang="en" class="English">No, I'm good.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0074.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">下手くそだもんね</p>      <p lang="en" class="English">Don't want to embarrass yourself, huh?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0075.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うるさいな</p>      <p lang="en" class="English">Oh, shut up.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0076.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ちーちゃんは武器持たないの？</p>      <p lang="en" class="English">You don't carry a weapon, right?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0077.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いらないよ　そんなの</p>      <p lang="en" class="English">I don't need one.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0078.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">たくさんあるのに</p>      <p lang="en" class="English">But there are so many just lying around.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0079.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ほとんどゴミでしょう</p>      <p lang="en" class="English">Those are basically all junk.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0080.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">でもまあ　もう少し探索してみようか</p>      <p lang="en" class="English">But I guess it wouldn't hurt to look for one that isn't.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0081.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">武器じゃなくてもさ　使えるものがあるかもしれない</p>      <p lang="en" class="English">Even if there aren't any weapons, we might find something else useful.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0082.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ご飯落ちてないかなぁ</p>      <p lang="en" class="English">Like food, maybe.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0083.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いや　ご飯は…</p>      <p lang="en" class="English">Well, in terms of food...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0084.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">レーションみたいなものなら　あるいは…</p>      <p lang="en" class="English">It'd probably be rations or something, or...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0085.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">機関銃</p>      <p lang="en" class="English">Machine gun.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0086.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">砲弾</p>      <p lang="en" class="English">Shells.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0087.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">戦車</p>      <p lang="en" class="English">Tank.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0088.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ねえ　戦車っておいしいかな</p>      <p lang="en" class="English">Hey, do you think tanks taste good?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0089.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">食べてみれば</p>      <p lang="en" class="English">Try it and find out.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0090.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ホントに食えよ</p>      <p lang="en" class="English">I'm serious.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0091.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">まるで武器の墓場だ</p>      <p lang="en" class="English">It's like a big weapon graveyard.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0092.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">昔の人も食料不足だったんだよね</p>      <p lang="en" class="English">The people of the past were short on food too, right?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0093.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">なんで武器ばっかり作ったの</p>      <p lang="en" class="English">So why'd they spend all their time making weapons?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0094.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">武器じゃなくて保存食をたくさん作ってくれれば 私たちも楽できたのに</p>      <p lang="en" class="English">It'd be a lot easier for us if these were all cans of food instead.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0095.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">まあ　いろいろ事情があったんでしょう</p>      <p lang="en" class="English">Well, they had other problems too, you know.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0096.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">戦争とか</p>      <p lang="en" class="English">Like war.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0097.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">すごい　飛行機だ</p>      <p lang="en" class="English">Wow! A plane!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0098.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">飛んでたのかな</p>      <p lang="en" class="English">Did it really fly?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0099.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">昔はね</p>      <p lang="en" class="English">A long time ago, yeah.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0100.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">飛んでみたいなぁ</p>      <p lang="en" class="English">I want to fly it.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0101.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">無理だろ</p>      <p lang="en" class="English">It won't work.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0102.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ちーちゃんも飛びたいだろ</p>      <p lang="en" class="English">Don't you want to fly too?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0103.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いや　全然</p>      <p lang="en" class="English">Nope, not at all.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0104.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">これも武器なのかな</p>      <p lang="en" class="English">Was this a weapon too?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0105.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">どうだろう</p>      <p lang="en" class="English">I wonder.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0106.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">でも　たぶん爆撃機とか　そういう…</p>      <p lang="en" class="English">Well, it was probably a bomber, or something like that...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0107.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">戦争って殺し合うんでしょう</p>      <p lang="en" class="English">War means killing each other, right?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0108.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">なんでそんなことするんだろうね</p>      <p lang="en" class="English">Why would anybody do that?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0109.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">さあ　相手と自分の利害が… 一致ぃ…ぃ…しなかったり</p>      <p lang="en" class="English">Who knows? Maybe if your best interests just don't coincide with theirs.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0110.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">例えば三人いるのに　食料が二人分しかないみたいな時に 武器を取って戦うしかなくなるんだよ　きっと</p>      <p lang="en" class="English">For example, if there are three of you, but only enough food for two, the only thing you can do is pick up your weapon and fight, probably.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0111.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">今も昔も変わらず</p>      <p lang="en" class="English">It was the same back then.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0112.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いろいろあるなぁ</p>      <p lang="en" class="English">There's all sorts of stuff here.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0113.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ちーちゃん　見てこれ　強そう</p>      <p lang="en" class="English">Chi-chan, check this out! It's huge!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0114.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">捨てなさい　銃なんていらないよ</p>      <p lang="en" class="English">Put it back. We don't need any guns.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0115.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">それより　使えるのが…</p>      <p lang="en" class="English">Way more useful than those are...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0116.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あった</p>      <p lang="en" class="English">Nice.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0117.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">爆薬</p>      <p lang="en" class="English">Explosives.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0118.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">そう これがあれば障害物を除けるたり　壁を壊したり</p>      <p lang="en" class="English">Yeah. With these, we'll be able to blow up obstacles and walls and stuff.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0119.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いっぱいあるね</p>      <p lang="en" class="English">There sure are a lot.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0120.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うん　積めるだけ積んで</p>      <p lang="en" class="English">Yeah. We'll take as many as we can.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0121.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あれ　ちーちゃん　これは</p>      <p lang="en" class="English">Huh? Chi-chan, what's this?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0122.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">何だろう</p>      <p lang="en" class="English">Hmm? I wonder.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0123.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">レーションか</p>      <p lang="en" class="English">Rations?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0124.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">運ぼう</p>      <p lang="en" class="English">Let's grab 'em.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0125.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">うん</p>      <p lang="en" class="English">Yeah!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0126.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">せーの</p>      <p lang="en" class="English">Heave ho!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0127.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">せーの</p>      <p lang="en" class="English">One, two!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0128.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ダメだ　やっぱり飛ばないなや</p>      <p lang="en" class="English">No use. Guess it really won't fly.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0129.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">飛ばなくていいって</p>      <p lang="en" class="English">It's not like we need it to, anyway.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0130.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">残念だな</p>      <p lang="en" class="English">Too bad, huh?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0131.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">全然</p>      <p lang="en" class="English">Not at all.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0132.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ほら　やっぱり飛ぶよ</p>      <p lang="en" class="English">Look! It works after all!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0133.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">飛ばないっての</p>      <p lang="en" class="English">No, it doesn't!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0134.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">飛んだ</p>      <p lang="en" class="English">I'm flying!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0135.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">お腹すいたね</p>      <p lang="en" class="English">You hungry?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0136.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ああ</p>      <p lang="en" class="English">Yeah.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0137.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">はい　ユーの分</p>      <p lang="en" class="English">All right, here's your half.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0138.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">どうも</p>      <p lang="en" class="English">Thanks.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0139.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ん　おいし</p>      <p lang="en" class="English">Tasty!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0140.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">チョコ味らしいよ</p>      <p lang="en" class="English">It says it's chocolate-flavored.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0141.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">チョコが何なのか知らんけど</p>      <p lang="en" class="English">No idea what chocolate is, though...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0142.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">あと１本</p>      <p lang="en" class="English">There's only one left.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0143.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">５本入りか　奇数だね</p>      <p lang="en" class="English">A five-pack? Odd number, huh?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0144.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">じゃあ半分こ…</p>      <p lang="en" class="English">Then, let's split it in half and...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0145.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">おい</p>      <p lang="en" class="English">Hey!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0146.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">動かないで</p>      <p lang="en" class="English">No sudden moves.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0147.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">何のつもりだ</p>      <p lang="en" class="English">What are you trying to pull?</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0148.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">これは私がもらう</p>      <p lang="en" class="English">This is mine now.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0149.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">なるほど　私も武器を持っておくべきだったか</p>      <p lang="en" class="English">I see. I should've been armed.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0150.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">そう</p>      <p lang="en" class="English">Yep.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0151.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">つまりこれが戦争</p>      <p lang="en" class="English">This is a war, after all.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0152.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ホントに食いやがった</p>      <p lang="en" class="English">Hey! You actually ate it!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0153.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">この野郎</p>      <p lang="en" class="English">Why, you!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0154.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">おい　ユーリ</p>      <p lang="en" class="English">Hey, Yuuri!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0155.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いたっ</p>      <p lang="en" class="English">Ow!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0156.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いたっ</p>      <p lang="en" class="English">Ow!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0157.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いったた　いたっ このっ　このっ</p>      <p lang="en" class="English">You, you...! Ow ow, ow!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0158.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">いたっいたっ　ホントに痛いってば このっ　このーっ</p>      <p lang="en" class="English">Ow, ow! You, you...! That actually hurts!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0159.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">このーっ　最後だったんじゃぞ ちーちゃん</p>      <p lang="en" class="English">You...! That was the last one! C'mon, Chi-chan!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0160.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">このーっ</p>      <p lang="en" class="English">You...!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0161.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">おいしかったー</p>      <p lang="en" class="English">That was tasty!</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0162.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">覚えてろよ</p>      <p lang="en" class="English">Y-You'll pay for this.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0163.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">動いて余計腹減った</p>      <p lang="en" class="English">I'm hungry again after all that.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0164.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">雪もおいしいよ</p>      <p lang="en" class="English">The snow's good, too.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0165.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">雪を食べなくちゃならないなんて</p>      <p lang="en" class="English">Having to eat snow, of all things...</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0166.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">ホントに戦争って嫌だね</p>      <p lang="en" class="English">War really is the worst.</p>    </figcaption>  </figure>  <hr>
<figure class="scene"><video playsinline controls preload="metadata"><source src="../Files/Girls Last Tour/A_Girl's_Last_Tour_S01_E01_0167.webm"  type="video/webm">    </video>    <figcaption>      <p lang="ja" class="Japanese">お前が言うな</p>      <p lang="en" class="English">I don't want to hear that from you.</p>    </figcaption>  </figure>  <hr>

  