window.lessonScenes = [

{
    type: "Summary",
        intro: `
        `
},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1712).jpg",japanese: "えー　しゅうちゃんも宿題　やってないの？<br>うしろ　自転車", english: "Whaaat, you haven't done your summer homework either ?<br>Bicycle behind you"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1713).jpg",japanese: "大丈夫だよ　あと十日もあるよ　十連休だよ", english: "It's okay, we still have ten days left, it's like a tenday vacation"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1714).jpg",japanese: "なるほど…<br>これから　十連休か…<br>素敵な　考え方だ…", english: "Huh ...<br>A ten-day vacation, huh?<br>That's a nice way to think about it"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1715).jpg",japanese: "とうちゃん<br>おとなりさん　いってくるなー<br>あいよ<br>(ふーか)ー　あははは　ははは！", english: "Daddy !!<br>I'm going next door !!<br>Okay<br>Fuuka! Ahhahahahaha!"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1716).jpg",japanese: "あー　(よつば)　ちゃんー", english: "Oh, Yotsuba-chan..."},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1717).jpg",japanese: "どうした？　どうした？<br>あれ？", english: "What's wrong !?<br>Huh !?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1718).jpg",japanese: "つくつくぼーしか？<br>なつおわる　からか？", english: "Is it the tsukutsuku boushi ?<br>Summer ends!?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1719).jpg",japanese: "終わったのは　夏じゃなくて<br>恋", english: "It wasn't summer that ended<br>It was my love"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1720).jpg",japanese: "…まあ　なか　に　はいれ<br>な？<br>…うん…　私の家だよ…", english: "...Why don't you come in...<br>...Okay ?<br>...I will... it is my house, after all..."},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1721).jpg",japanese: "とにかく　のめ<br>な？", english: "Anyway, drink...<br>...Okay ?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1722).jpg",japanese: "どんなときも　ぎゅうにゅうだぞ？", english: "Milk is good any time!"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1723).jpg",japanese: "なにがあったのか<br>(よつば)に　はなしてみろ？<br>な？<br>うん", english: "What happened ?<br>Tell Yotsuba ...<br>...Okay ?<br>Okay"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1724).jpg",japanese: "私ね…　好きな男の子が　いたのね…<br>ああー…", english: "See... there was this guy I liked...<br>Ahhhh ..."},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1725).jpg",japanese: "こいかー…", english: "Love, huh...?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1726).jpg",japanese: "(ふーか)はもう　チューしたか？<br>……　してない", english: "Fuuka kissed him?<br>...... no"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1727).jpg",japanese: "そっかー　まだかー…", english: "I see, not yet..."},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1728).jpg",japanese: "……私も　それなりには<br>少しは　モテたこと　あるのよ", english: "...I'm actually ...<br>...Kind of popular with the guys, you know"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1729).jpg",japanese: "ラブレター　もらったことも　あるんだから<br>ラブレター？", english: "I've even gotten a love letter<br>Love letter !?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1730).jpg",japanese: "すきです", english: "i love you"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1731).jpg",japanese: "ってかいてある　やつか？<br>そうそれ！<br>かいてあったか？　すきですって　かいてあったか？<br>かいてあった！", english: "You mean that kind of thing !?<br>Yeah, that's it!<br>Did it really say that!? Did it really say \"i love you\"!?<br>Yeah, it did !"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1732).jpg",japanese: "おー", english: "O h h h h h h !!"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1733).jpg",japanese: "みせて！<br>それ　みせて！<br>いやだよ<br>見せるもんじゃないのよ", english: "Let me see!<br>Let me see it!<br>No way!<br>That's not the kind of thing you show somebody"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1734).jpg",japanese: "チューした？　そいつと　チューした？<br>だから　しないって<br>お断りした　から<br>ごめんなさいって", english: "Did you kiss him!? Did you kiss the guy!?<br>No, like I told you, I didn't<br>I turned him down<br>* I said sorry"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1735).jpg",japanese: "おことわりって　なにー？<br>えー　おつきあい　できませんってこと", english: "What's \"turned him down\"?<br>It means we couldn't be boyfriend and girlfriend"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1736).jpg",japanese: "なんで　できないの？<br>ラブレターくれた人は　好きな人と　ちがったから", english: "Why not?<br>The person who sent me the love letter wasn't the person I liked"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1737).jpg",japanese: "ふーん", english: "Hmm..."},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1738).jpg",japanese: "すきなひとに　ラブレター　もらったらいいのに<br>そうだね<br>もったく　そうだね", english: "You should get a love letter from the person you like<br>You're right<br>You are so right"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1739).jpg",japanese: "でもその好きな　人はね<br>さっきうちの学校の　女の子とね<br>手ぇつないで　歩いてたの", english: "But I just saw the guy I like...<br>...Walking hand in hand with ...<br>...Another girl from my school"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1740).jpg",japanese: "なかいいな？<br>いいよね", english: "They're friends ?<br>Yup, they are"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1741).jpg",japanese: "…つまりー<br>私の好きな　男の子は<br>おつきあいしてる　女の子がいたの<br>わかる？", english: "...In other words ...<br>...The boy I like...<br>... already has a girlfriend<br>Understand?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1742).jpg",japanese: "…えで　せつめいして<br>え", english: "Explain with a drawing<br>Eh?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1743).jpg",japanese: "(ふーか)　へただから　よくわかんない", english: "Fuuka's bad at drawing, so I don't really get it"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1744).jpg",japanese: "えっと…<br>じゃあ(よつば)ちゃんで　言うと…", english: "Umm ...<br>Okay, I'll use you as an example"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1745).jpg",japanese: "(よつば)ちゃんは　誰が好き？<br>とうちゃん！", english: "Who do you like, Yotsuba-chan?<br>D a d d y !"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1746).jpg",japanese: "じゃあ<br>とうちゃんは　(よつば)ちゃんのこと　好きじゃなかった<br>そんな感じ", english: "Okay<br>Then imagine if your dad didn't like you<br>It's like that"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1747).jpg",japanese: "あ", english: "Ah"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1748).jpg",japanese: "わー<br>ちがう！　うそっ！　とうちゃん　(よつば)ちゃん　大好きっ！", english: "W a a a a a h !!<br>No, wait! That's not true! Your dad really loves you!"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1749).jpg",japanese: "たとえば！<br>失恋の　たとえ話ね？<br>ね？<br>あー！　たとえばなー？<br>びっくり　したなー", english: "It was just an example!<br>That's just what heartbreak is like, okay !?<br>Okay !?<br>Oooh! An example ?<br>You scared me"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1750).jpg",japanese: "あ<br>わかった！　(ふーか)！<br>ん？", english: "Oh!<br>I get it, fuuka!<br>Hn ?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1751).jpg",japanese: "(ふーか)は　しつれんしました！<br>あ　そうです　わかってくれましたか", english: "You have heartbreak !!<br>Yes, that's right, you understand now?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1752).jpg",japanese: "しつれんだ　……<br>しまったぁー　……", english: "Heartbreak...<br>Oh no......"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1753).jpg",japanese: "しつれんって　あれな？<br>しんだり　ころしたり　するやつ…<br>えっと<br>あー…<br>そーね…　死んだり殺したり　するよね…", english: "Heartbreak is...<br>...That thing that dies and kills people, right...!?<br>Umm ....<br>Uhh ...<br>Yeah... that's what it does, it dies and kills people..."},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1754).jpg",japanese: "まってろ！<br>あー　(よつば)ちゃん", english: "Wait here !<br>Uh, Yotsuba-chan"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1755).jpg",japanese: "このことは　みんなには　ないしょよ？<br>わかってる！", english: "Keep this a secret from everyone, okay?<br>Okay !!"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1756).jpg",japanese: "いいか？　しぬなよ！<br>はい", english: "Don't die, all right !?<br>I won't"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1757).jpg",japanese: "ころすなよ？<br>はい", english: "Don't kill anyone, all right !?<br>I won't"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1758).jpg",japanese: "お？<br>どうしたの？　血相かえて", english: "Huh ?<br>What's the matter? You're as pale as a ghost"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1759).jpg",japanese: "(ふーか)が　しつれんした！<br>ありゃま", english: "Fuuka's got heartbreak !<br>Oh, dear"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1760).jpg",japanese: "しつれんしたら　どうしたらいい？<br>どうしたらなおる？", english: "What do you do for heartbreak !?<br>How do you make it better !?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1761).jpg",japanese: "私<br>フラれたこと　ないからよく　わかんないな<br>おー…", english: "Well ...<br>...I've never been rejected, so I wouldn't know<br>Oh ...."},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1762).jpg",japanese: "(風香)ちゃん　あんだけかわいくても　フラれるのか…<br>意外だな<br>(ふーか)　かわいいな？<br>男の子に受けそーな　スタイルしてるしね", english: "Even someone as cute as Fuukachan got rejected ?<br>That's surprising<br>Fuuka's cute, right ?<br>And she has the kind of look that I'd think the boys would like"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1763).jpg",japanese: "…足はちょっと　太いかな<br>(ふーか)　あしふといな？<br>男の子には　あれくらいがいいのよ<br>トラ子は細すぎだね", english: "...Maybe her legs are a little fat, though<br>Fuuka has fat legs, right?<br>That's the size guys like them<br>You're just too skinny, torako"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1764).jpg",japanese: "(よつば)は　どうしたらいい？<br>んー　そうね<br>てきとうに　元気づけてやって", english: "What should Yotsuba do?<br>Hmm, let's see...<br>Just do whatever you can think of to cheer her up"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1765).jpg",japanese: "よしっ", english: "Okay !"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1766).jpg",japanese: "あれ？　(よつば)ちゃん", english: "Huh? Oh hi, Yotsuba-chan"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1767).jpg",japanese: "(えな)には　まだはやい", english: "It's too soon for you, ena!"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1768).jpg",japanese: "(えな)はへやで　べんきょうしてろ！<br>えー　なにそれー", english: "You go back in your room and study !<br>Huh? What was that about?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1769).jpg",japanese: "ただいま<br>あ！　かあちゃん　かえってきた！", english: "I'm home<br>Oh! Good timing, mom!"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1770).jpg",japanese: "かあちゃんは　しつれん　しってるか？<br>へ？　失恋？", english: "Do you know about heartbreak?<br>Huh!? Heartbreak!?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1771).jpg",japanese: "あはははは　このー<br>おませさん", english: "Ah ha ha ha ha<br>You're precocious, huh?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1772).jpg",japanese: "しつれんは　おませさんか？<br>おませさんよ", english: "Heartbreak is precocious ?<br>It is"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1773).jpg",japanese: "(ふーか)　おませさん…<br>あ　(風香)なの？　そりゃ大変だ", english: "Fuuka's precocious ...<br>Oh, it's Fuuka? That's bad"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1774).jpg",japanese: "たいへんか？　しょんぼりしちゃう？<br>そーよ　ちょーしょんぼりよ", english: "It's bad? Like, it makes you get sad?<br>That's right, it makes you really sad"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1775).jpg",japanese: "(よつば)はとうちゃんに　おこられたら　しょんぼりする<br>それくらい？<br>もっと　もっと　しょんぼりよ", english: "Yotsuba gets sad when my dad yells at me<br>Is it like that ?<br>Much, much sadder !!"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1776).jpg",japanese: "あ", english: "Ah"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1777).jpg",japanese: "だいじょぶか？<br>そんなことして　くるしくないか？<br>……　ちょっと　くるしい…", english: "Are you okay !?<br>Isn't it hard to breathe like that!?<br>....Yeah, kinda..."},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1778).jpg",japanese: "でも本当に　苦しいのは…<br>心<br>なに　いってんだ？<br>だいじょぶか？", english: "But what really makes it hard is...<br>...The pain in my heart<br>What do you mean!?<br>Are you okay !?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1779).jpg",japanese: "えっと<br>えっと<br>なん　だっけ", english: "Umm ...<br>Umm ...<br>What did it again?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1780).jpg",japanese: "おまーせ　さん！", english: "You're precocious !"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1781).jpg",japanese: "(ふーか)は　おませさんだな！<br>おませさん！", english: "Fuuka's precocious !<br>Precocious !"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1782).jpg",japanese: "だから　げんきだせ！<br>しょんぼり　するな！", english: "So cheer up!<br>Don't be sad!"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1783).jpg",japanese: "(あさぎ)は　しつれんしたこと　ないんだぞ！", english: "Asagi's never had heartbreak!"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1784).jpg",japanese: "(あさぎ)は　だいじょぶだ！<br>あんしんしろ！", english: "Asagi's fine!<br>So don't worry !"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1785).jpg",japanese: "えっと　それからぁー<br>(ふーか)は　あし　ふといな！", english: "Umm... what else...<br>You have fat legs!"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1786).jpg",japanese: "ふともも　ぐにょぐにょだな！", english: "Your thighs are mushy too!"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1787).jpg",japanese: "それでも　しぬな！<br>な？<br>うう…", english: "But don't die, okay?<br>Okay !?<br>Uugh ..."},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1788).jpg",japanese: "(風香)　どうなってる？<br>悪趣味ね　あんた", english: "How is Fuuka doing ?<br>You're evil, you know that?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1789).jpg",japanese: "お母さんだって　覗いてるじゃない<br>親はいいのよ　親は", english: "Hey, you're watching her too<br>I'm her mother, so I'm allowed"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1790).jpg",japanese: "しなないよ…", english: "I won't die..."},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1791).jpg",japanese: "私は夏の終わりが　くるたびに<br>恋の終わりを　思いだすの　かしらね<br>さようなら　私の恋", english: "I wonder if, when summer ends...<br>...I'll remember the end of my love<br>Goodbye my love"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1792).jpg",japanese: "グッバイ　マイラブ<br>…あれあなたの　娘さんですよ<br>あんたの妹よ", english: "So long, my love<br>...She's your daughter, you know<br>And she's your sister"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1793).jpg",japanese: "もうしつれん　おわーたー？", english: "Your heartbreak ended now?"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1794).jpg",japanese: "…そうね<br>終わりにしなくちゃ　いけないよね<br>うん　もうやめとけ？", english: "... you're right<br>I have to end it<br>Yeah, just quit it already"},
{type: "Immersion",image: "../Files/Yotsuba/Yotsuba (1795).jpg",japanese: "わかった…<br>私　前を向いて　歩いていく<br>この足で<br>ふとい　あしでな", english: "That's it...<br>I'm going to start walking forward ...<br>...On my own two legs<br>Your two fat legs"},





];